# define parameters for calibration and identification process
# robot: staubli TX40
---
calibration:
  calib_level:
  non_geom:
  base_frame:
  tool_frame:
  markers:
    - ref_joint:
      measure: []
  free_flyer:
  nb_sample:
identification:
  robot_params:
    - q_lim_def: 1.57
      fv : [8.05e0, 5.53e0, 1.97e0, 1.11e0, 1.86e0, 6.5e-1]
      fs : [7.14e0, 8.26e0, 6.34e0, 2.48e0, 3.03e0, 2.82e-1]
      Ia : [3.62e-1, 3.62e-1, 9.88e-2, 3.13e-2, 4.68e-2, 1.05e-2]
      offset : [3.92e-1, 1.37, 3.26e-1, -1.02e-1, -2.88e-2, 1.27e-1]
      Iam6 : 9.64e-3
      fvm6 : 6.16e-1
      fsm6 : 1.95e0
      N : [32.0, 32.0, 45.0, -48.0, 45.0, 32.0]
      ratio_essential : 30.0
      dq_lim_def : [0.05009095, 0.05009095, 0.07504916, 0.0715585,  0.05585054, 0.12217305]
      ddq_lim_def : 20.0
      tau_lim_def : 4.0
  problem_params:
    - is_external_wrench : False
      is_joint_torques : True
      force_torque : None
      external_wrench_offsets : False
      has_friction : True
      has_joint_offset : True
      has_actuator_inertia : True
      is_static_regressor : True
      is_inertia_regressor : True
      has_coupled_wrist: True
      embedded_forces : False
  processing_params:
    - cut_off_frequency_butterworth: 100.0
      ts : 0.0002
  tls_params:
    - mass_load : 0.0
      which_body_loaded : 0.0
      sync_joint_motion : False
...
