pre-commit:
  variables:
    CACHE: ${CI_PROJECT_DIR}/.cache
    PIP_CACHE: ${CACHE}/pip
    PRE_COMMIT_HOME: ${CACHE}/pre-commit
  cache:
    paths:
      - ${CACHE}
  image: python
  before_script: python -m pip --cache-dir ${PIP_CACHE} install pre-commit
  script: pre-commit run -a

test:
  image: docker
  variables:
    DOCKER_BUILDKIT: 1
  script:
    - docker build -t figaroh .
    - docker run --rm -t figaroh
