ci:
    autoupdate_branch: 'devel'
repos:
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v14.0.5
    hooks:
    -   id: clang-format
        args: [--style=Google]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-added-large-files
        args: ['--maxkb=100000']
        exclude: |
            (?x)^(
                models/.*|
            )$
    -   id: check-ast
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: debug-statements
    -   id: trailing-whitespace
-   repo: https://github.com/PyCQA/flake8
    rev: 6.1.0  # Updated to latest stable version
    hooks:
    -   id: flake8
        args: ['--ignore=E501']
        additional_dependencies: ['importlib-metadata<7.0']
